services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: compassway/backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./data:/app/data